# Generated by Django 4.2.3 on 2023-07-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
