# Generated by Django 4.2.3 on 2023-08-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newgame',
            name='image',
            field=models.ImageField(default='new_game_image/default.jpg', upload_to='new_game_image/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='video',
            field=models.FileField(blank=True, upload_to='preview/%Y/%m/%d'),
        ),
    ]
