# Generated by Django 4.2.5 on 2023-10-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newgame',
            name='genre2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Жанр игры 2'),
        ),
        migrations.AddField(
            model_name='newgame',
            name='genre3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Жанр игры 3'),
        ),
    ]
