# Generated by Django 4.2.3 on 2023-08-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_games', '0002_alter_newgame_image_alter_newgame_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newgame',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='newgame',
            name='genre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='video',
            field=models.FileField(blank=True, default='preview/default.mp4', upload_to='preview/%Y/%m/%d'),
        ),
    ]
