# Generated by Django 4.2.3 on 2023-08-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_games', '0003_alter_newgame_options_newgame_genre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newgame',
            options={'ordering': ['title'], 'verbose_name': 'Анонс игры', 'verbose_name_plural': 'Анонс игр'},
        ),
        migrations.AddField(
            model_name='newgame',
            name='create',
            field=models.DateField(blank=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='description',
            field=models.TextField(verbose_name='Описание игры'),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='genre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Жанр игры'),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='image',
            field=models.ImageField(default='new_game_image/default.jpg', upload_to='new_game_image/%Y/%m/%d/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название игры'),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='video',
            field=models.FileField(blank=True, default='preview/default.mp4', upload_to='preview/%Y/%m/%d', verbose_name='Трейлер'),
        ),
    ]
