# Generated by Django 4.2.3 on 2023-08-13 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_games', '0004_alter_newgame_options_newgame_create_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('game_commented', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='new_games.newgame', verbose_name='Комментируемая игра')),
            ],
        ),
    ]
