# Generated by Django 4.2.3 on 2023-08-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_games', '0006_comments_comment_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-comment_created'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Комментатор'),
        ),
    ]
