# Generated by Django 4.2.3 on 2023-08-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_games', '0007_alter_comments_options_alter_comments_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
