# Generated by Django 4.2.3 on 2023-08-14 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_games', '0008_comments_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['comment_created'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
