# Generated by Django 4.2.3 on 2023-09-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_games', '0009_alter_comments_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='favourite_game',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='favourite_genre',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
