# Generated by Django 4.2.5 on 2023-10-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_games', '0012_alter_newgame_options_newgame_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newgame',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг от экспертов на Metarankings.ru'),
        ),
    ]
