# Generated by Django 4.2.5 on 2023-10-17 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_options_alter_profile_avatar_and_more'),
        ('new_games', '0013_alter_newgame_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='newgame',
            name='rating_site',
            field=models.FloatField(default=0, verbose_name='Рейтинг нашего сайта'),
        ),
        migrations.CreateModel(
            name='NewVoteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.IntegerField(blank=True, null=True, verbose_name='Оценка игры пользователем')),
                ('game_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_games.newgame', verbose_name='Для какой игры оценка')),
                ('user_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='Кто оценивает игру')),
            ],
            options={
                'verbose_name': 'Оценку игры',
                'verbose_name_plural': 'Оценка игры',
            },
        ),
    ]
