# Generated by Django 4.2.3 on 2023-08-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название игры')),
                ('genre', models.CharField(max_length=250, verbose_name='Жанр игры')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
                ('description', models.TextField(verbose_name='Содержание')),
                ('game_image', models.ImageField(blank=True, null=True, upload_to='game_image/%Y/%m/%d/', verbose_name='Обложка')),
                ('created', models.DateField(verbose_name='Дата написания статьи')),
            ],
        ),
    ]
