# Generated by Django 4.2.3 on 2023-09-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help_games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['title'], 'verbose_name': 'игру', 'verbose_name_plural': 'Игры'},
        ),
    ]
