# Generated by Django 4.2.5 on 2023-09-22 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help_games', '0002_alter_game_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_title', models.CharField(max_length=200, verbose_name='Название подсказки')),
                ('hint_description', models.TextField(verbose_name='Описание подсказки')),
                ('hint_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='help_games.game', verbose_name='Для какой игры подсказка')),
            ],
            options={
                'verbose_name': 'подсказку',
                'verbose_name_plural': 'Подсказки',
                'ordering': ['hint_game'],
            },
        ),
    ]
