# Generated by Django 4.2.5 on 2023-09-22 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help_games', '0003_hint'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=200, verbose_name='Название видео обзора')),
                ('video_description', models.FileField(blank=True, default='preview/default.mp4', upload_to='videoview/%Y/%m/%d', verbose_name='Видео обзор')),
                ('video_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='help_games.game', verbose_name='Для какой игры обзор')),
            ],
        ),
    ]
