# Generated by Django 4.2.5 on 2023-09-22 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help_games', '0005_alter_videoview_options_gamecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamecomment',
            options={'ordering': ['-comment_created'], 'verbose_name': 'комментарий к игре', 'verbose_name_plural': 'Комментарии к игре'},
        ),
    ]
