# Generated by Django 4.2.5 on 2023-09-22 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help_games', '0006_alter_gamecomment_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamecomment',
            old_name='game_commented',
            new_name='comment_game',
        ),
    ]
