# Generated by Django 4.2.5 on 2023-10-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_games', '0007_rename_game_commented_gamecomment_comment_game'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-rating', 'title'], 'verbose_name': 'игру', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='videoview',
            name='video_description',
            field=models.URLField(max_length=300, verbose_name='Видео обзор'),
        ),
    ]
