# Generated by Django 4.2.5 on 2023-10-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_games', '0008_alter_game_options_game_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг игроков от Metarankings.ru'),
        ),
    ]
